from typing import Protocol, Optional, List

from src.core.models import (
	 User,
	 UserProfile,
	 UserPreferences,
	 FitnessGoal,
	 UserMemory,
	 ExerciseDefinition,
	 Workout,
	 WorkoutExercise,
	 ExerciseSet,
	 PersonalRecord,
)

# User domain
class UserRepository(Protocol):
	 def save(self, user: User) -> User: ...

	 def find_by_id(self, user_id: str) -> Optional[User]: ...

	 def find_by_email(self, email: str) -> Optional[User]: ...

	 def find_by_username(self, username: str) -> Optional[User]: ...

	 def update(self, user: User) -> User: ...


class UserProfileRepository(Protocol):
	 def save(self, profile: UserProfile) -> UserProfile: ...

	 def find_by_user_id(self, user_id: str) -> Optional[UserProfile]: ...

	 def update(self, profile: UserProfile) -> UserProfile: ...


class UserPreferencesRepository(Protocol):
	 def save(self, prefs: UserPreferences) -> UserPreferences: ...

	 def find_by_user_id(self, user_id: str) -> Optional[UserPreferences]: ...

	 def update(self, prefs: UserPreferences) -> UserPreferences: ...


class FitnessGoalRepository(Protocol):
	 def save(self, goal: FitnessGoal) -> FitnessGoal: ...

	 def find_by_id(self, goal_id: str) -> Optional[FitnessGoal]: ...

	 def list_by_user(self, user_id: str, active_only: bool = True) -> List[FitnessGoal]: ...

	 def update(self, goal: FitnessGoal) -> FitnessGoal: ...


class UserMemoryRepository(Protocol):
	 def save(self, memory: UserMemory) -> UserMemory: ...

	 def list_active_by_user(self, user_id: str) -> List[UserMemory]: ...

	 def update(self, memory: UserMemory) -> UserMemory: ...


# Workout domain
class ExerciseDefinitionRepository(Protocol):
	 def save(self, ex: ExerciseDefinition) -> ExerciseDefinition: ...

	 def get_by_id(self, exercise_id: str) -> Optional[ExerciseDefinition]: ...

	 def find_by_name(self, name: str) -> Optional[ExerciseDefinition]: ...

	 def search(self, *, muscle_groups: Optional[List[str]] = None, equipment: Optional[List[str]] = None) -> List[ExerciseDefinition]: ...


class WorkoutRepository(Protocol):
	 def save(self, workout: Workout) -> Workout: ...

	 def get_by_id(self, workout_id: str) -> Optional[Workout]: ...

	 def update(self, workout: Workout) -> Workout: ...

	 def list_by_user_recent(self, user_id: str, limit: int = 20) -> List[Workout]: ...


class WorkoutExerciseRepository(Protocol):
	 def save(self, we: WorkoutExercise) -> WorkoutExercise: ...

	 def list_by_workout(self, workout_id: str) -> List[WorkoutExercise]: ...

	 def get_by_id(self, workout_exercise_id: str) -> Optional[WorkoutExercise]: ...


class ExerciseSetRepository(Protocol):
	 def save(self, s: ExerciseSet) -> ExerciseSet: ...

	 def list_for_workout_exercise(self, workout_exercise_id: str) -> List[ExerciseSet]: ...


class PersonalRecordRepository(Protocol):
	 def save(self, pr: PersonalRecord) -> PersonalRecord: ...

	 def list_by_user_and_exercise(self, user_id: str, exercise_id: str) -> List[PersonalRecord]: ...

	 def get_best_one_rm(self, user_id: str, exercise_id: str) -> Optional[PersonalRecord]: ...


